2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_setup.py:_flush():76] Current SDK version is 0.17.4
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_setup.py:_flush():76] Configure stats pid to 47991
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_setup.py:_flush():76] Loading settings from /Users/scanner1/.config/wandb/settings
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_setup.py:_flush():76] Loading settings from /Users/scanner1/Downloads/capdock/src/src/logs/runs/2024-07-17/16-29-48/wandb/settings
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_service_wait': '300'}
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/src/run.py', 'program_abspath': '/Users/scanner1/Downloads/capdock/src/src/run.py', 'program': '/Users/scanner1/Downloads/capdock/src/src/run.py'}
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_init.py:_log_setup():529] Logging user logs to ./wandb/run-20240717_163108-2bt72vx3/logs/debug.log
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_init.py:_log_setup():530] Logging internal logs to ./wandb/run-20240717_163108-2bt72vx3/logs/debug-internal.log
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_init.py:init():569] calling init triggers
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {}
2024-07-17 16:31:08,705 INFO    MainThread:47991 [wandb_init.py:init():619] starting backend
2024-07-17 16:31:08,706 INFO    MainThread:47991 [wandb_init.py:init():623] setting up manager
2024-07-17 16:31:08,708 INFO    MainThread:47991 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-07-17 16:31:08,710 INFO    MainThread:47991 [wandb_init.py:init():631] backend started and connected
2024-07-17 16:31:08,719 INFO    MainThread:47991 [wandb_init.py:init():720] updated telemetry
2024-07-17 16:31:08,735 INFO    MainThread:47991 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-07-17 16:31:08,906 ERROR   MainThread:47991 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-17 16:31:08,907 ERROR   MainThread:47991 [wandb_init.py:init():1191] error in wandb.init()
Traceback (most recent call last):
  File "/Users/scanner1/opt/anaconda3/envs/capdock/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    return wi.init()
  File "/Users/scanner1/opt/anaconda3/envs/capdock/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-17 16:31:09,991 WARNING MsgRouterThr:47991 [router.py:message_loop():77] message_loop has been closed
